/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsIdRouteImport } from './routes/hosts.$id'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as HostsIdIndexRouteImport } from './routes/hosts.$id.index'
import { Route as EventsIdIndexRouteImport } from './routes/events.$id.index'
import { Route as HostsIdEditRouteImport } from './routes/hosts.$id.edit'
import { Route as EventsIdEditRouteImport } from './routes/events.$id.edit'
import { Route as EventsIdCheckInRouteImport } from './routes/events.$id.check-in'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIdRoute = HostsIdRouteImport.update({
  id: '/hosts/$id',
  path: '/hosts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIdIndexRoute = HostsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HostsIdRoute,
} as any)
const EventsIdIndexRoute = EventsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsIdRoute,
} as any)
const HostsIdEditRoute = HostsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => HostsIdRoute,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EventsIdRoute,
} as any)
const EventsIdCheckInRoute = EventsIdCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => EventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/check-in': typeof EventsIdCheckInRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/hosts/$id/edit': typeof HostsIdEditRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/hosts/$id/': typeof HostsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/new': typeof EventsNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/check-in': typeof EventsIdCheckInRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/hosts/$id/edit': typeof HostsIdEditRoute
  '/events/$id': typeof EventsIdIndexRoute
  '/hosts/$id': typeof HostsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/check-in': typeof EventsIdCheckInRoute
  '/events/$id/edit': typeof EventsIdEditRoute
  '/hosts/$id/edit': typeof HostsIdEditRoute
  '/events/$id/': typeof EventsIdIndexRoute
  '/hosts/$id/': typeof HostsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events/$id/check-in'
    | '/events/$id/edit'
    | '/hosts/$id/edit'
    | '/events/$id/'
    | '/hosts/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/events/new'
    | '/invite/$token'
    | '/events/$id/check-in'
    | '/events/$id/edit'
    | '/hosts/$id/edit'
    | '/events/$id'
    | '/hosts/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/explore'
    | '/login'
    | '/my-events'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events/$id/check-in'
    | '/events/$id/edit'
    | '/hosts/$id/edit'
    | '/events/$id/'
    | '/hosts/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  SignupRoute: typeof SignupRoute
  TicketsRoute: typeof TicketsRoute
  EventsIdRoute: typeof EventsIdRouteWithChildren
  EventsNewRoute: typeof EventsNewRoute
  HostsIdRoute: typeof HostsIdRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$id': {
      id: '/hosts/$id'
      path: '/hosts/$id'
      fullPath: '/hosts/$id'
      preLoaderRoute: typeof HostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$id/': {
      id: '/hosts/$id/'
      path: '/'
      fullPath: '/hosts/$id/'
      preLoaderRoute: typeof HostsIdIndexRouteImport
      parentRoute: typeof HostsIdRoute
    }
    '/events/$id/': {
      id: '/events/$id/'
      path: '/'
      fullPath: '/events/$id/'
      preLoaderRoute: typeof EventsIdIndexRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/hosts/$id/edit': {
      id: '/hosts/$id/edit'
      path: '/edit'
      fullPath: '/hosts/$id/edit'
      preLoaderRoute: typeof HostsIdEditRouteImport
      parentRoute: typeof HostsIdRoute
    }
    '/events/$id/edit': {
      id: '/events/$id/edit'
      path: '/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/events/$id/check-in': {
      id: '/events/$id/check-in'
      path: '/check-in'
      fullPath: '/events/$id/check-in'
      preLoaderRoute: typeof EventsIdCheckInRouteImport
      parentRoute: typeof EventsIdRoute
    }
  }
}

interface EventsIdRouteChildren {
  EventsIdCheckInRoute: typeof EventsIdCheckInRoute
  EventsIdEditRoute: typeof EventsIdEditRoute
  EventsIdIndexRoute: typeof EventsIdIndexRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdCheckInRoute: EventsIdCheckInRoute,
  EventsIdEditRoute: EventsIdEditRoute,
  EventsIdIndexRoute: EventsIdIndexRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

interface HostsIdRouteChildren {
  HostsIdEditRoute: typeof HostsIdEditRoute
  HostsIdIndexRoute: typeof HostsIdIndexRoute
}

const HostsIdRouteChildren: HostsIdRouteChildren = {
  HostsIdEditRoute: HostsIdEditRoute,
  HostsIdIndexRoute: HostsIdIndexRoute,
}

const HostsIdRouteWithChildren =
  HostsIdRoute._addFileChildren(HostsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  SignupRoute: SignupRoute,
  TicketsRoute: TicketsRoute,
  EventsIdRoute: EventsIdRouteWithChildren,
  EventsNewRoute: EventsNewRoute,
  HostsIdRoute: HostsIdRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
